### ISSUE TITLE
How to create an archive?

### ISSUE THREAD

**Issue by ghost** [michaelmaniscalco/m19#1]
@michaelmaniscalco Thank you for your hard work,

I compiled m19 using `scons`, but now how can I create an archive ( compress & decompress)?
```
home@home-lnx:~/m19/build/release/bin$ ./m19 9 test.txt 
m19 - next generation BWT compressor.  Author: M.A. Maniscalco (2018 - 2019)
*** This build is pre-alpha and demonstrates both M19 and M03 context parsing only ***
max order = 5                               
elapsed time: 4335 ms, 15.683 MB/sec
```

**Comment by michaelmaniscalco** [comment]
Hi,

m19 is a work in progress.  It doesn't yet have the encoder or decoder attached.  Currently, it only has the engine for parsing the BWT output using the context boundaries of the original input.  So there is still some work remaining before it is can compress/decompress.

On github, only my m99 and m03 compressors are completed and working.  m19 will probably be completed within the next three to six months as time permits.

- Michael

**Comment by MrOCR** [comment]
Thanks, keep up the good work

**Comment by ghost** [comment]
Though, how does m19 compared to nanozip?

**Comment by ghost** [comment]
@michaelmaniscalco 
Also, can you recommend to me the best archive that can compress a txt file with permutation structure:
```
aaaa
aaab
aaac
.
.
.
zzzy
zzzz
```

**Comment by michaelmaniscalco** [comment]
Since m19 is not complete I can't make a comparison.  However, m19 will be at least as strong as m03 - which is about the strongest BWT there is.  However, it is a pure generic compressor for the purposes of advancing BWT specifically.  

nanozip et al are not generic compressors.  They use lots of different compression algorithms and filters to increase compression based on the type of data being encoded.

As to best archive for your data, have a look at http://www.mattmahoney.net/dc/text.html for a list of possibilties to check out.  Or, better yet post your question at https://encode.ru 
That's where all the experts hang out and you'll get lots of advice there.

- Michael
